# Generated by Django 2.0 on 2018-08-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('bio', models.TextField(max_length=500, verbose_name='Bio')),
            ],
            options={
                'db_table': 'author',
                'verbose_name_plural': 'Authors',
                'verbose_name': 'Author',
            },
        ),
    ]
